name: fetch-and-generate-fortran-package
on:
  push:
    branches:
      - main
env:
  GCC_V: "11"
  PROJECT_NAME: "fortran-unicode"
  BRANCH_NAME: ${{ env.PROJECT_NAME }}-fpm
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.x

    - name: Install fypp
      run: pip install --upgrade fypp
    
    - name: Generate ${{ env.PROJECT_NAME }}-fpm package 🔧
      run: |
        make # Run make
        mkdir ${{ env.BRANCH_NAME }} # 
        ./get_unicode_data.sh # Get the NameLists.txt
        cp -R src   ${{ env.BRANCH_NAME }}
        cp -R test  ${{ env.BRANCH_NAME }}
        cp fpm.toml ${{ env.BRANCH_NAME }}
        cp LICENSE  ${{ env.BRANCH_NAME }}
    
    - name: Install GFortran
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ env.GCC_V }} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ env.GCC_V }} \
        --slave /usr/bin/gcov gcov /usr/bin/gcov-${{ env.GCC_V }}
    
    - name: Install fpm latest release
      uses: fortran-lang/setup-fpm@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run fpm build ⚙
      run: |
        fpm build --profile release

    # Update and deploy the f90 files generated by github-ci to the `PROJECT_NAME-fpm` branch.
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      if: github.event_name != 'pull_request'
      with:
        BRANCH: ${{ env.BRANCH_NAME }}
        FOLDER: ${{ env.BRANCH_NAME }}
